CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Controllers/EducationCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Danyl.SnnuURP.WebUI.Areas.Teacher.Controllers
{
    public class EducationCenterController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Teach()
        {
            List<Danyl.SnnuURP.Model.TeachCourseView> teachList = new BLL.TeachCourseView().GetModelList(" Tid= " + this.HttpContext.Session["userid"].ToString());
            ViewBag.TeachList = teachList;
            return View(ViewBag);
        }

        public ActionResult StudentGrade()
        {
            List<Danyl.SnnuURP.Model.TeacherScoreView> scoreList = new BLL.TeacherScoreView().GetModelList(" Tid= " + this.HttpContext.Session["userid"].ToString());
            ViewBag.ScoreList = scoreList;
            return View(ViewBag);
        }

        public ActionResult MyBook()
        {
            return View();
        }
    }
}

CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Controllers/FinancialCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Danyl.SnnuURP.Model;

namespace Danyl.SnnuURP.WebUI.Areas.Teacher.Controllers
{
    public class FinancialCenterController : Controller
    {
        // GET: Teacher/FinancialCenter
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MyFinancial()
        {
            List<TeacherWageAdjustmentView> teacherWage = new BLL.TeacherWageAdjustmentView().GetModelList(" Tid=" + Session["userid"].ToString());
            ViewBag.TeacherWageList = teacherWage;
            return View();
        }
    }
}

CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Danyl.SnnuURP.WebUI.Areas.Teacher.Controllers
{
    public class MaterialController : Controller
    {
        // GET: Teacher/Material
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Download()
        {
            return View();
        }
    }
}

CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Controllers/MessegeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Danyl.SnnuURP.WebUI.Areas.Teacher.Controllers
{
    public class MessegeController : Controller
    {
        // GET: Teacher/Messege
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CollegeMsg()
        {
            ViewBag.CollegeMsg = null;
            return View(ViewBag);
        }
        
        public ActionResult LetterMsg()
        {
            ViewBag.LetterMsg = null;
            return View(ViewBag);
        }

        public ActionResult Advice()
        {
            ViewBag.Advice = null;
            return View(ViewBag);
        }
    }
}

CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Controllers/MyInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Danyl.SnnuURP.WebUI.Areas.Teacher.Controllers
{
    public class MyInfoController : Controller
    {
        // GET: Teacher/MyInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Info()
        {
            int Tid = Convert.ToInt32(HttpContext.Session["userid"]);
            Danyl.SnnuURP.Model.Teacher teacher = new BLL.Teacher().GetModel(Tid);
            try
            {
                Danyl.SnnuURP.Model.Depart depart = new BLL.Depart().GetModel(teacher.DeptId);
                Danyl.SnnuURP.Model.TeacherType TType = new BLL.TeacherType().GetModel(teacher.TeacherTypeId);
                Danyl.SnnuURP.Model.UserInfo userInfo = new BLL.UserInfo().GetModel(Tid);
                ViewBag.Tid = teacher.Tid;
                ViewBag.Tname = teacher.Tname;
                ViewBag.Sex = teacher.Sex ? '男' : '女';
                ViewBag.IdNumber = teacher.IdNumber;
                ViewBag.Depart = depart.DeptName;
                ViewBag.Degree = teacher.Degree;
                ViewBag.TeacherType = TType.TeacherTypes;
                ViewBag.Phone = userInfo.UserPhone;
                ViewBag.Email = userInfo.UserEmail;
                return View(ViewBag);
            }
            catch (Exception ex)
            {
                return Redirect("~/Teacher/Account/Login");
            }
        }
    }
}

CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Views/MyInfo/Index.cshtml
@{
    ViewBag.Title = "个人中心";
    Layout = "~/Areas/Teacher/Views/Shared/_Layout.cshtml";
}

<h2 class="mbx">
    个人中心&nbsp;&nbsp;&nbsp;&nbsp;
</h2>
<div class="dhbg">
    <div class="dh1" style="margin: 0 27px 15px 0;">
        <div class="dhwz">
            <p>
                您共有 <span class="red">0</span>条通知信息 <span class="red">0 </span>条未读
            </p>
            <p>
                共有 <span class="red">0 </span>条短信息、 <span class="red">0</span>个投诉、 <span class="red">
                    0
                </span>个异议
            </p>
            <p>
                有 <span class="red">0</span>个投诉、<span class="red">
                    0
                </span>个异议、<span class="red">0</span>条短信息未处理
            </p>
            <div class="btright">
                <a href=@Url.Action("LetterMsg","Messege")>
                    <img src="~/Images/Teacher/default/bt_bzr.jpg" alt="给学院发消息" width="121" height="25" />
                </a>
            </div>
        </div>
    </div>
    <div class="dh2">
        <div class="dhwz">
            <p>
                你有 <span class="red">0</span> 门课程 <a href=@Url.Action("StudentGrade","EducationCenter") class="red">查看教学计划</a>
            </p>
            <p>
                本学期 <span class="red">0 </span>门课程&nbsp;共有 <span class="red">2</span> 门 <a href=@Url.Action("StudentGrade","EducationCenter") class="red">查看成绩</a>
            </p>
            <p>
                已经发放了 <span class="red">0 </span>本书籍 <a href=@Url.Action("StudentGrade","EducationCenter") class="red">查看书籍情况</a>
            </p>
            <div class="btright">
                <a href=@Url.Action("StudentGrade","EducationCenter")>
                    <img src="~/Images/Teacher/default/bt_jw.jpg" alt="进入教务中心" width="121" height="25" />
                </a>
            </div>
        </div>
    </div>
    <div class="dh3" style="margin: 0 27px 15px 0;">
        <div class="dhwz">
            <p>
                <a href="#">模拟考试</a>
            </p>
            <p>
                <a href="#">章节练习</a>
            </p>
            <p>
                <a href="#">网上作业</a>
            </p>
            <div class="btright">
                <a href=@Url.Action("Download","Material")>
                    <img src="~/Images/Teacher/default/bt_ks.jpg" alt="进入资料下载中心" width="121" height="25" />
                </a>
            </div>
        </div>
    </div>
    <div class="dh4">
        <div class="dhwz">
            <p>
                你总共有<span class="red">3</span> 条财务记录需要确定
            </p>
            <p>
                本月工资发放情况
            </p>
            <p>
                工资调整信息
            </p>
            <div class="btright">
                <a href=@Url.Action("MyFinancial","FinancialCenter")>
                    <img src="~/Images/Teacher/default/bt_cw.jpg" alt="进入财务中心" width="121" height="25" />
                </a>
            </div>
        </div>
    </div>
</div>

CSharp/教务管理系统网站设计/SnnuURP (内含数据库)/Danyl.SnnuURP.WebUI/Areas/Teacher/Views/MyInfo/Info.cshtml
@{
    ViewBag.Title = "我的信息";
    Layout = "~/Areas/Teacher/Views/Shared/_Layout.cshtml";
}

<h2 class="mbx">我的信息 &gt; 个人资料 &nbsp;&nbsp;&nbsp;</h2>
<div class="cztable">
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="right" width="80">姓名：</td>
            <td>@ViewBag.Tname&nbsp;</td>
            <td align="right" width="90">身份证号码：</td>
            <td>@ViewBag.IdNumber&nbsp;</td>

            <td rowspan="9"><div align="center"><img id="pic_face" height="160" width="120" src="/Images/Teacher/photo.jpg" style="padding:2px 2px 5px; border:1px #ddd solid;"></div>&nbsp;</td>
        </tr>
        <tr>
            <td align="right">性别：</td>
            <td>@ViewBag.Sex&nbsp;</td>
            <td align="right">工号：</td>
            <td>@ViewBag.Tid&nbsp;</td>
        </tr>
        <tr>
            <td align="right">所属学院：</td>
            <td>@ViewBag.Depart&nbsp;</td>
            <td align="right">学位：</td>
            <td>@ViewBag.Degree&nbsp;</td>
        </tr>
        <tr>
            <td align="right">教师类型：</td>
            <td>@ViewBag.TeacherType&nbsp;</td>
            <td align="right">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>

        <tr>
            <td colspan="4" align="left">联系方式（如联系方式有变动请及时修改，以便能及时联系到你。谢谢！）</td>
        </tr>
        <tr>
            <td align="right">手机号码：</td>
            <td>@ViewBag.Phone</td>
            <td align="right">第二联系号码：</td>
            <td></td>
        </tr>
        <tr>
            <td align="right">QQ:</td>
            <td></td>
            <td align="right">电子邮箱：</td>
            <td>@ViewBag.Email</td>
        </tr>
        <tr align="center">
            <td colspan="5" height="40">
                <div align="center">
                    <input type="button" id="button2" value="联系方式有修改" onclick="submitMail()" class="input2" />
                </div>
            </td>
        </tr>
    </table>
</div>